### ISSUE TITLE
/data/common.yaml - file does not contain a valid yaml hash

### ISSUE THREAD

**Issue by WBasson** [pcfens/puppet-static_custom_facts#6]
Puppet complains that common.yaml does not contain a valid yaml hash. Should it change from
`---`
to
`--- {}`
?

**Comment by pcfens** [comment]
Thanks for catching this. Can you test out the latest commit to see if that fixes things? If it does I'll tag a new release and publish it to the forge.

**Comment by WBasson** [comment]
It does indeed, thank you very much.

**Comment by jcpunk** [comment]
I suspect time got away from you, can this fix be put on the forge?

**Comment by pcfens** [comment]
Thanks for the reminder. I just pushed this in 0.3.2.
